---
title: "SortTimes"
author: "Samyak Ahuja"
date: "August 23, 2018"
output: pdf_document
---

```{r include=FALSE}
library(ggplot2)
library(ggpmisc)
library(reshape2)
```

# Complexity for different Sorting Algorithms.

## Helper Functions

### Replicator

```{r}
replicator <- function(func, size = 1000){
  if(size == 1000){
      ele <- seq(from = 0, to = 1000, by = 50)
  }else{
      ele <- seq(from = 0, to = 10000, by = 250)
  }
  ele <- ele[-1]
  timeElapsed <- c()
  for(n in ele){
    op <- 0
    for(i in 1:10){
         op = op + func(sample(x = 1:100, size = n, replace = TRUE))$operations
    }
    op = op / 10
    timeElapsed <- c(timeElapsed, op)
  }
  return (data.frame(ele,timeElapsed))
}
```

### Plotter

```{r}
plotter <- function(df, df_title){
  ggplot(df, aes(ele, timeElapsed, color = timeElapsed)) +
    geom_point(shape = 16, size = 5, show.legend = FALSE, alpha = 0.6) + 
    stat_smooth(method="lm", formula=y~poly(x,2), rm = FALSE) + 
    theme_minimal() + 
    labs(subtitle = "Time vs Size",
       y = "Number of Comparisons (Averaged)",
       x = "Number of Elements",
       title = df_title) +
    scale_color_gradient(low = "#32aeff", high = "#f2aeff") +
    stat_poly_eq(parse=T, aes(label = ..eq.label..), formula=y~poly(x,2))
}
```

### Combined Plotter
```{r}
comb_plotter <- function(df, df_title){
  ggplot(df, aes(ele, value, col = variable)) + 
  geom_point(shape = 16, size = 2, alpha = 0.6) + 
  stat_smooth(method="lm", formula=y~poly(x,2)) + 
  theme_minimal() +
  labs(subtitle = "Time vs Size",
       y = "Number of Comparisons (Averaged)",
       x = "Number of Elements",
       title = df_title) +
  stat_poly_eq(parse=T, aes(label = ..eq.label..), formula=y~poly(x,2)) 
}
```

## Insertion Sort

### Sorting Algorithm
```{r}
insertionSort <- function(vec){
  n <- length(vec)
  op <- 0
  for(i in 2:n){
    key <- vec[i]
    pos <- i - 1
    while(pos > 0 && vec[pos] > key){
      vec[pos + 1] = vec[pos]
      pos = pos - 1
      op <- op + 1
    }
    vec[pos + 1] <- key
    op <- op + 1
  }
  return (list("vec" = vec, "operations" = op))
}
```

### Proof of concept
```{r}
insertionSort(c(12,-22,13,2,-33,2))
```

### RunTime and Plot
```{r}
isdf_small <- replicator(insertionSort)
isdf_small
plotter(isdf_small, "Insertion Sort - Small N")
```

```{r eval=FALSE, include=FALSE}
isdf_big <- replicator(insertionSort, 10000)
isdf_big
plotter(isdf_big, "Insertion Sort - Large N")
```


## Merge Sort

### Sorting Algorithm

```{r}
mergeSort <- function(vec){
  
  mergeTwo <- function(left,right){
    op <- 0
    res <- c()
    while(length(left) > 0 && length(right) > 0){
      op <- op + 1
      if(left[1] <= right[1]){
        res <- c(res,left[1])
        left <- left[-1]  
      }else{
        res <- c(res,right[1])
        right <- right[-1]
      }
    }
    if(length(left) > 0){
      res <- c(res,left)
    }
    if(length(right) > 0){
      res <- c(res,right)
    }
    return (list("vec" = res, "operations" = op))
  }
  
  op <- 0
  n <- length(vec)
  if(n <= 1) return (list("vec" = vec, "operations" = op))
  else{
    middle <- length(vec) %/% 2 #integer division
    left_list <- mergeSort(vec[1:middle])
    right_list <- mergeSort(vec[(middle + 1):n])
    left <- left_list$vec
    right <- right_list$vec
    res <- mergeTwo(left,right)
    op <- op + left_list$operations + right_list$operations + res$operations
    return (list("vec" = res$vec, "operations" = op))
  }
}
```

### Proof of Concept
```{r}
mergeSort(c(12,-22,13,2,-33,2))
```

### RunTime and Plot
```{r}
msdf_small <- replicator(mergeSort)
msdf_small
plotter(msdf_small, "Merge Sort - Small N")
```

```{r eval=FALSE, include=FALSE}
msdf_big <- replicator(mergeSort, 10000)
msdf_big
plotter(msdf_big, "Merge Sort - Large N")
```


## Quick Sort

### Sorting Algorithm

```{r}
quickSort <- function(vec, low = 1, high = length(vec)){
  
  partition <- function(vec, low, high){
    i = low
    op <- 0
    pivot = vec[high]
    for(j in low:(high - 1)){
      op <- op + 1 
      if(vec[j] <= pivot){
        temp = vec[i]
        vec[i] = vec[j]
        vec[j] = temp
        i = i + 1
      }
    }
    temp = vec[i]
    vec[i] = vec[high]
    vec[high] = temp
    return (list("vec" = vec, "operations" = op, "pi" = i))
  }
  
  op <- 0
  if(low < high){
    pi_list = partition(vec, low, high)
    vec <- pi_list$vec
    pi <- pi_list$pi
    
    left_list <- quickSort(vec, low, pi - 1)
    vec <- left_list$vec
    
    right_list <- quickSort(vec, pi + 1, high)
    vec <- right_list$vec
    
    op <- op + left_list$operations + right_list$operations + pi_list$operations
    return (list("vec" = vec, "operations" = op))
  }else{
    return (list("vec" = vec, "operations" = op))
  }
}
```

### Proof of Concept
```{r}
quickSort(c(12,-22,13,2,-33,2))
```

### RunTime and Plot
```{r}
qsdf_small <- replicator(quickSort)
qsdf_small
plotter(qsdf_small, "Quick Sort - Small N")
```

```{r eval=FALSE, include=FALSE}
qsdf_big <- replicator(quickSort, 10000)
qsdf_big
plotter(qsdf_big, "Quick Sort - large N")
```


## Combined Plots

```{r}
df_small <- data.frame(ele = msdf_small[[1]],
                 insertionSort = isdf_small[[2]], 
                 mergeSort = msdf_small[[2]], 
                 quickSort = qsdf_small[[2]])
df_small
df_small <- melt(df_small, id.vars = "ele")
comb_plotter(df_small, "Combined Scatter Plot for small N")
```

```{r eval=FALSE, include=FALSE}
df_big <- data.frame(insertionSort = isdf_big[[2]], 
                 mergeSort = msdf_big[[2]], 
                 quickSort = qsdf_big[[2]], 
                 ele = msdf_big[[1]])
df_big
df_big <- melt(df_big, id.vars = "ele")
comb_plotter(df_big, "Combined Scatter Plot for large N")
```
